name: Pruebas API TiendaRopa

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3


    - name: Verificar que la API en ngrok responde
      run: |
        echo "Verificando que la API en $NGROK_URL responde..."
        curl --fail $NGROK_URL || exit 1
      env:
        NGROK_URL: ${{ secrets.NGROK_URL }}

    - name: Instalar Newman y HTML Reporter
      run: |
        npm install -g newman newman-reporter-html

    - name: Ejecutar pruebas Postman (contra ngrok)
      run: |
        mkdir -p newman
        newman run "Pruebas_API_TiendaRopa.postman_collection.json" \
          # URL variable secreta para nuevas ejecuciónes ngrok
          --env-var "base_url=${{ secrets.NGROK_URL }}" \
          --reporters cli,json,html \
          --reporter-json-export newman/results.json \
          --reporter-html-export newman/report.html

    - name: Subir reportes de Newman
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reportes-newman
        path: newman/
